name:                mac-assistant
version:             0.1.0.0
github:              "tiagofmcosta/mac-assistant"
license:             BSD3
author:              "Tiago Costa"
maintainer:          "costa.tiago@gmail.com"
copyright:           "2021 Tiago Costa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tiagofmcosta/mac-assistant#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- wreq
- lens
- bytestring
- text
- containers
- aeson
- string-interpolate
- uri-encode
- http-client
- time
- simple-logger

library:
  source-dirs: src

executables:
  mac-assistant:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mac-assistant

tests:
  mac-assistant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mac-assistant
